---
docker_package: docker-ce
docker_version: "18.03.1"
docker_storage_driver: "overlay2"
docker_config_file: "/etc/sysconfig/docker"
docker_systemd_service_path: "/etc/systemd/system/docker.service.d"
docker_suse_extension: 'sle-module-containers/12/x86_64'
docker_suse_ha_extension: 'sle-ha/{{ ansible_distribution_version }}/x86_64' 
