version: '3.6'
services:
  jenkins:
    image: "demo-jenkins:lts"
    tty: true
    network_mode: "bridge"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - jenkins_data:/var/jenkins_home
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}/{{.Name}}"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 5000
        published: 5000
        protocol: tcp
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: "start-first"
    healthcheck:
      test: nc -z localhost 8080
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 1m30s
  nginx:
    image: "nginx"
    tty: true
    network_mode: "bridge"
    volumes:
      - /opt/jenkins/nginx_vhost.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/private/self_signed.key:/etc/ssl/private/self_signed.key
      - /etc/ssl/certs/self_signed.crt:/etc/ssl/certs/self_signed.crt
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}/{{.Name}}"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: "start-first"

volumes:
  jenkins_data:
